# Generated by Django 5.2.8 on 2025-11-28 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('lemonade', 'Lemonade Stand'), ('toy_shop', 'Toy Shop'), ('restaurant', 'Restaurant'), ('bakery', 'Bakery'), ('farm', 'Farm'), ('tech', 'Tech Startup')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('initial_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_limit', models.IntegerField(help_text='Time limit in minutes')),
                ('points_reward', models.IntegerField(default=50)),
                ('coins_reward', models.IntegerField(default=25)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('suggested_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('icon', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='scenarios.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('weather', 'Weather'), ('customer', 'Customer'), ('market', 'Market'), ('special', 'Special')], max_length=20)),
                ('impact_text', models.CharField(max_length=200)),
                ('probability', models.IntegerField(default=20, help_text='Probability percentage')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scenarios.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='UserScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=20)),
                ('current_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('days_played', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attempts', to='scenarios.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scenarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('expense', 'Expense')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=200)),
                ('day', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenarios.product')),
                ('user_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='scenarios.userscenario')),
            ],
            options={
                'ordering': ['day', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.product')),
                ('user_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='scenarios.userscenario')),
            ],
            options={
                'unique_together': {('user_scenario', 'product')},
            },
        ),
    ]
