# Generated by Django 5.2.8 on 2025-11-30 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='المعرف')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('icon', models.CharField(max_length=10, verbose_name='الأيقونة')),
                ('difficulty', models.CharField(choices=[('easy', 'سهل'), ('medium', 'متوسط'), ('hard', 'صعب')], max_length=20, verbose_name='الصعوبة')),
                ('capital', models.IntegerField(default=50, verbose_name='رأس المال')),
                ('duration', models.CharField(default='10-15', max_length=50, verbose_name='المدة')),
                ('age_range', models.CharField(default='8-12', max_length=50, verbose_name='الفئة العمرية')),
                ('points_reward', models.IntegerField(default=50, verbose_name='مكافأة النقاط')),
                ('coins_reward', models.IntegerField(default=25, verbose_name='مكافأة العملات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'سيناريو',
                'verbose_name_plural': 'السيناريوهات',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='in_progress', max_length=20, verbose_name='الحالة')),
                ('score', models.IntegerField(default=0, verbose_name='النتيجة')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البدء')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attempts', to='scenarios.scenario', verbose_name='السيناريو')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scenarios', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سيناريو المستخدم',
                'verbose_name_plural': 'سيناريوهات المستخدمين',
                'ordering': ['-started_at'],
            },
        ),
    ]
