# Generated by Django 5.2.8 on 2025-11-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscenario',
            name='days_played',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userscenario',
            name='final_reputation',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='userscenario',
            name='game_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userscenario',
            name='items_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscenario',
            name='last_played',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userscenario',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
